
  virtueTexts = {
    "Tolerance": "Diversity glorifies the garden of life. That's why you like different flowers in your bouquet of friends.",
    "Contentment": "Just by writing a list of your achievements you realize that you have everything you need.",
    "Compassion": "You perceive needs without judging and send out good wishes.",
    "Brotherhood": "Because you know the father every human being has become your brother.",
    "Simplicity": "You see the essentials in the charms of life and light your load by letting go of complications.",
    "Courage": "You have won your greatest battle by agreeing to change",
    "Patience": "Knowing the tiny seed contains the future tree you let your success grow in the soil of constancy",
    "Discipline": "You obey the natural laws of the universe and receive in return protection, abundance and peace of mind",
    "Delicacy": "You make magic wands of your thoughts and actions to turn vulgarity into subtlety",
    "Humility": "You are a spiritual warrior who lays down the weapons of arrogance and resists to the pleasures of praise",
    "Spontaneity": "Your spontaneity is like a gurgling brook which quenches all thirsts and lightens burdens",
    "Responsibility": "Knowing your role is UNIQUE, you are the hero, not the spectator, in the drama of life",
    "Harmony": "When you let go, you see how life dances",
    "Wisdom": "You balance masterly depth and childlike lightness and learn something new in every situation",
    "Faith": "You remove any doubt that blocks your path forward",
    "Friendship": "You are your own best friend",
    "Happiness": "You receive the little miracles of daily life as winks from the divine",
    "Self-confidence": "You accept your good points with humility and simply dare to be great",
    "Detachment": "You know that less expectations means less disappointment",
    "Enthusiasm": "By listening to the child inside you, you give souls wings to fly",
    "Discernment": "When in doubt, you know you can trust your instinct",
    "Purity": "Your inner beauty shines in your eyes. Each one of our qualities is a facet of the diamond within",
    "Hope": "You know each trial is like a friend that helps you grow stronger. That's why you always try again.",
    "Freedom": "You look without judging. Listen without being influenced. Enjoy without greed",
    "Creativity": "The foundation of creativity is inner peace",
    "Concentration": "When the mind has become still and focused, then even thought that arises will hit the target without fail",
    "Strength": "Connection with truth brings strength to the soul. The greater the truth the more powerful the strength.",
    "Serenity": "The knowledge of the self is equivalent to truth which brings serenity and spiritual beauty",
    "Respect": "The foundation of respect lies in the ability to accept another without judgement, irrespective of anything else",
    "Lightness": "Be in the moment, without the burden of the past or the pressure of the future. This state of being is true lightness",
    "Honesty": "Honesty is not just being natural, but giving to ourselves what is good and positive",
    "Generosity": "The greatest act of generosity is to see beyond the weaknesses and mistakes of others",
    "Flexibility": "The moment I renounce desire of ‘wanting’, I become flexible internally and externally. I become free",
    "Economy": "Economy means to have a focused mind that does not lose time with waste thoughts",
    "Determination": "The moment I renounce desire of ‘wanting’, I become flexible internally and externally. I become free"
  };
  months = {
    "0": "January",
    "1": "February",
    "2": "March",
    "3": "April",
    "4": "May",
    "5": "June",
    "6": "July",
    "7": "August",
    "8": "September",
    "9": "October",
    "10": "November",
    "11": "December"
  };
  i18n = {
    "OK": "OK",
    "Cancel": "Cancel",
    "Hide history": "Hide history",
    "No history yet": "No history yet",
    "Date": "Date",
    "Virtue": "Virtue",
    "Hide": "Hide",
    "Show": "Show",
    "Work in progress": "Work in progress",
    "Next month": "Next month",
    "Show history": "Show history",
    "Hide Images": "Hide Images",
    "Show Images": "Show Images",
    "Cards with text will be displayed.": "Cards with text will be displayed.",
    "Start Year Plan": "Virtuescope Predictions",
    "Restart": "Restart",
    "Running": "Running",
    "Download PDF": "Download PDF",
    "Send Email": "Send Email",
    "Pause": "Pause",
    "Play": "Spin",
    "Play again": "Spin again",
    "Virtuescope": "Virtuescope",
    "Virtuescope Predictions": "Virtuescope Predictions",
    "Please enter your email": "Please enter your email",
    "Please wait": "Please wait ...",
    "Email sent successfully !": "Email sent successfully !",
    "Email could not be sent (how embarassing !). Please download the PDF.": "Email could not be sent (how embarassing !). Please download the PDF.",
    "introText": "Every day spin the wheel and enjoy the magic : keeping in mind that quality, see how it colours your thoughts, your environment, your world.",
    "meditateNow": "Meditate Now",
    "back": "Back"
  };
  plans = {
    "7 days": "7 days",
    "3 months": "3 months",
    "6 months": "6 months",
    "12 months": "12 months"
  };
  plansLength = {
    "7 days": "7d",
    "3 months": "3",
    "6 months": "6",
    "12 months": "12",
    "4 months": "4",
    "15 days": "15d"
  }
